### ISSUE TITLE
The conflicting result files of FVC

### ISSUE THREAD

**Issue by liu-xu-bing** [yyren/FVC#1]
Hello, I ran FVC in a WGS file and got 5 files in the end: RP-347-8_test_out_indel.out, RP-347-8_test_out_snv.out, RP-347-8_filtered.vcf, FVC_predict_indel.txt, FVC_predict_snv.txt. I thought FVC_predict_* files are the lable and probability of each variant, but I found a variant is 0 and probability is 0.0012222216 in FVC_predict_snv.txt but in RP-347-8_filtered.vcf FVC=1 and FILTER=PASS. So which result should I use and why does FVC make this result? 
-------------------------------------------------------------------
FVC_predict_snv.txt
chr     loc0    loc1    ref     target  prediction      probability
11      7694640 7694640 A       *,T,<NON_REF>   0       0.0012222216

RP-347-8_filtered.vcf
11      7694640 .       A       *,T,<NON_REF>   0       PASS    DP=73;ExcessHet=0.0000;MLEAC=1,0,0;MLEAF=0.500,0.00,0.00;MQRankSum=0.000;RAW_MQandDP=262800,73;ReadPosRankSum=2.285;FVC=1     GT:AD:DP:GQ:PGT:PID:PL:PS:SB    1|0:33,30,0,0:63:99:0|1:7694612_GT_G:1409,0,1278,1245,1323,2563,1389,1365,2587,2730:7694612:21,12,21,9
-------------------------------------------------------------------

**Comment by yyren** [comment]
Hi Liu,
Could you please provide the VCF file with the target variant and the bam file including the region chr11:7693640-7695640? Furthermore, what is the genome version used in the reads alignment?

**Comment by liu-xu-bing** [comment]
Hi Ren
Here are the vcf file and bam file in attechment and the ref file I use is ensembl release-80 Homo_sapiens.GRCh38.dna.primary_assembly.fa. The vcf file is generated by GATK HaplotypeCaller. Here is the command when I ran the FVC:

bash ~/software/FVC/Features_construction.sh -i RP-347-8.g.vcf -b RP-347-8_markdup.bam -r Homo_sapiens.GRCh38.dna.primar -p RP-347-8_test_out_snv.out -q RP-347-8_test_out_indel.out
bash ~/software/FVC/Supervised_learning_filtering.sh -f filter -i RP-347-8.g.vcf -o RP-347-8_filtered.vcf -p RP-347-8_test_out_snv.out -q RP-347-8_test_out_indel.out -m /home/liuxubing/software/FVC/Pre-trained_Models/gatk_snv_xgbdef.model -n /home/liuxubing/software/FVC/Pre-trained_Models/gatk_indel_xgbdef.model

**Comment by yyren** [comment]
Hi Liu,
I am sorry I can not find the attached files both here and in my email. Could you please provide a website where I can download or send the files to my email: yongyong.ren@sjtu.edu.cn

**Comment by yyren** [comment]
Hi Liu, 
Thank you for pointing out this problem. 
The predicted results of the SNVs (RP-347-8_test_out_snv.out) were not combined into the final results. We have updated the script '[merge_predict_results.pl](https://github.com/yyren/FVC/blob/main/merge_predict_results.pl)'. 
Please contact me if you have any other questions.

**Comment by liu-xu-bing** [comment]
Hi Ren
I have tested the new FVC and got the right result. 
Thank you.
